Update repo structure
qbicsoftware/subscription-service pull request #12
Opened 2022-02-03 09:47 UTC by sven1103

2022-02-03 12:16 UTC, KochTobi approved these changes
LGTM

2022-02-07 08:08 UTC, jenniferboedker commented on LICENSE
> +Copyright (c) 2022 Sven Fillinger
should be university of tübingen

2022-02-07 08:52 UTC, jenniferboedker commented
Also the new workflow files are missing (release, publish-snapshots)

2022-02-07 08:53 UTC, jenniferboedker requested changes
See my previous comments

2022-02-08 09:38 UTC, jenniferboedker approved these changes
LGTM

2022-02-08 09:40 UTC, merged